### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#573]
After considering the differences between Flow and TypeScript 2.0 I'm thinking I'd like to try moving decaffeinate to TypeScript 2.0. @alangpierce's [comment](https://github.com/decaffeinate/coffee-lex/commit/4ad21045ecef2942832acb6f73141dfbcfa91882#commitcomment-19895726) is pretty spot-on in terms of where the two projects stand. There probably isn't enough benefit to justify the switch purely on technical merit. However, both @alangpierce and I have been looking for an opportunity to dig deeper into TypeScript and using decaffeinate for that purpose seems reasonable.

## Why?

- In my experience, my editor (WebStorm) has better support for TypeScript than for Flow.
- TypeScript has superior tooling, especially around bringing types in from the `@types` npm namespace and automatic generation of `.d.ts` files.
- Now that `strictNullChecks` is an option, my favorite feature from Flow is also in TypeScript (non-nullable types).
- Configuring babel is somewhat of a headache, and I really only ever use the es2015 preset plus a handful of things, all of which are supported by TypeScript.

## Roadmap

- [x] coffee-lex (https://github.com/decaffeinate/coffee-lex/pull/77)
  - [x] remove .flowconfig
  - [x] add tsconfig.json
  - [x] rename sources to use `.ts` extension
  - [x] configure rollup
  - [x] fix type errors
  - [x] ~emit types for `dist` files~ (https://github.com/rollup/rollup-plugin-typescript/issues/54)
  - [x] refactor token types to use an `enum` (**breaking change**, assign explicit number values to prevent reordering issues)
  - [x] remove `coffee-lex.js.flow` once all other projects are converted
- [x] decaffeinate-parser
  - [x] add tsconfig.json
  - [x] rename sources to use `.ts` extension
  - [x] configure rollup
  - [x] fix type errors
- [ ] decaffeinate-traverse
  - [ ] remove .flowconfig
  - [ ] add tsconfig.json
  - [ ] rename sources to use `.ts` extension
  - [ ] configure rollup
  - [ ] fix type errors
- [ ] decaffeinate
  - [ ] remove .flowconfig
  - [ ] add tsconfig.json
  - [ ] rename sources to use `.ts` extension
  - [ ] configure rollup
  - [ ] fix type errors

I don't want this to interfere with any of your work, @alangpierce, so I'll try to do things in small chunks that are unlikely to cause problems.

**Comment by alangpierce** [comment]
Cool, sounds good to me! If all goes well, I just have one more commit in decaffeinate-parser and one more commit in decaffeinate to wrap up #557. Probably I won't be making any big changes after that, at least not for a while, so you should be free to make changes without worrying too much about conflicts.

**Comment by alangpierce** [comment]
Thanks for getting this kicked off. Some thoughts from trying out coffee-lex in WebStorm:

It looks like WebStorm doesn't recognize the mocha-typescript style of mocha tests. I really like being able to press Ctrl+Shift+R (to run) or Ctrl+Shift+D (to debug) within an individual test when I'm working with it, which means WebStorm needs to be able to parse the test file. Also, the mocha runner was just running the compiled JS, so I would need to set breakpoints in JS code under the normal mocha config. I was able to get things working for me with a few tweaks:
* Install ts-node as a dev dependency and add `--compilers ts:ts-node/register` in the mocha options for the default WebStorm mocha config. Although probably that could also just go in mocha.opts.
* Change the code back to `describe`/`it` style so WebStorm can recognize it. To get this to type check, I used `tsd install mocha --save` as described here: http://jonnyreeves.co.uk/2015/hello-typescript-and-mocha/ .

That makes running/debugging tests in development work nicely. I can send a PR for that stuff if you agree that it's a good change.

Also, the build artifacts (.js and .d.ts files) are next to the .ts files, and I don't see any way to clean them. Might be nice to make an npm script for that, or maybe typescript has a way to do that, or maybe it's best to move them out to a build directory or something. When I was trying out different mocha options, it was complaining about `.d.ts` files and it was discovering both `.ts` and `.js` files, so it was running twice as many tests as it should.

**Comment by eventualbuddha** [comment]
I'd be happy to look at a PR for these changes. I agree that the mocha-typescript stuff is worse in WebStorm. Also, `tsd` shouldn't really be needed anymore, right? Can just do `npm install --save-dev @types/mocha` I think.

**Comment by alangpierce** [comment]
Yep, I'm sure `@types/mocha` is better, I'm certainly new to all this stuff. I'll probably put up a PR for that this weekend.

**Comment by alangpierce** [comment]
The core decaffeinate project is 100% TypeScript now, so I'm going to call this a success and close the issue. Technically decaffeinate-traverse is still JavaScript, but it's not used at the moment, so seems low priority. It also might be nice to move bulk-decaffeinate and decaffeinate-examples to TS eventually, but I'll call that out of scope for now. Given that decaffeinate produces JavaScript, might be nice to have at least a little plain JavaScript. 😄
